import { useState } from "react";
import { track } from "@vercel/analytics";
import type { BorrowerProfile, Mix, MixResult, Assumptions } from "../types";
import type { PrintMode } from "./PrintSummary";
import { ShareLinks } from "./ShareLinks";
import { getTrack } from "../engine/tracks";
import { formatCurrency, formatPercent } from "../engine/format";
import { useLang } from "../i18n";
import { navySelectedShadow, softCardBorder, softCardGradient, softCardShadow } from "../styles/brand";

/**
 * Bank X-Frame-Options/CSP headers block embedding their sites, so the
 * hand-off is: take your summary (print/copy), then open the bank's own
 * digital ishur-ikaroni flow in a new tab / call their mortgage line.
 * Plain outbound links only — no affiliation, no referral compensation
 * (see spec section 9, regulatory posture).
 */
const BANKS = [
  {
    nameEn: "Bank Leumi",
    nameHe: "בנק לאומי",
    mark: "L",
    color: "#004B9B",
    url: "https://www.leumi.co.il",
    phone: "*3200",
  },
  {
    nameEn: "Bank Hapoalim",
    nameHe: "בנק הפועלים",
    mark: "P",
    color: "#D71920",
    url: "https://www.bankhapoalim.co.il",
    phone: "*2408",
  },
  {
    nameEn: "Mizrahi-Tefahot",
    nameHe: "מזרחי-טפחות",
    mark: "M",
    color: "#F47B20",
    url: "https://www.mizrahi-tefahot.co.il",
    phone: "*8860",
  },
  {
    nameEn: "Discount Bank",
    nameHe: "בנק דיסקונט",
    mark: "D",
    color: "#009B77",
    url: "https://www.discountbank.co.il",
    phone: "*2009",
  },
];

function buildTextSummary(
  profile: BorrowerProfile,
  mix: Mix,
  result: MixResult,
  assumptions: Assumptions,
  lang: string
): string {
  const he = lang === "he";
  const lines: string[] = [];
  lines.push(he ? "— בדיקת מוכנות למשכנתא של VryfID —" : "— VryfID Mortgage Readiness Check —");
  lines.push(new Date().toLocaleDateString(he ? "he-IL" : "en-GB"));
  lines.push("");
  lines.push(
    `${he ? "מחיר הנכס" : "Property price"}: ${formatCurrency(profile.propertyPrice)} | ${he ? "הון עצמי" : "Equity"}: ${formatCurrency(profile.ownEquity)} | ${he ? "הלוואה" : "Loan"}: ${formatCurrency(result.loanAmount)} (LTV ${formatPercent(result.ltv)})`
  );
  lines.push(
    `${he ? "הכנסה נטו" : "Net income"}: ${formatCurrency(profile.monthlyNetIncome)}/mo | ${he ? "חוב קיים" : "Existing debt"}: ${formatCurrency(profile.existingMonthlyDebt)}/mo | ${he ? "גיל הלווה המבוגר" : "Age of older borrower"}: ${profile.olderBorrowerAge} | ${he ? "תקופה" : "Term"}: ${result.effectiveTermYears}y`
  );
  lines.push("");
  lines.push(he ? "התמהיל:" : "Mix:");
  for (const alloc of mix.allocations) {
    if (alloc.percent <= 0) continue;
    const track = getTrack(alloc.trackId);
    lines.push(`  • ${he ? track.nameHe : track.name} — ${alloc.percent}% @ ${(alloc.annualRate * 100).toFixed(2)}%`);
  }
  lines.push("");
  lines.push(
    `${he ? "החזר היום" : "Payment today"}: ${formatCurrency(result.paymentToday)}/mo | ${he ? "החזר מקסימלי צפוי" : "Highest expected"}: ${formatCurrency(result.paymentStressed)}/mo`
  );
  lines.push(
    `${he ? "סך ריבית (תרחיש קיצון)" : "Total interest (stressed)"}: ${formatCurrency(result.totalInterestStressed)} | ${he ? "תרחיש בסיס" : "baseline"}: ${formatCurrency(result.totalInterestBaseline)}`
  );
  lines.push(
    `PTI ${formatPercent(result.pti)} | ${he ? "רכיב קבוע" : "Fixed"} ${formatPercent(result.fixedShare)} | ${he ? "בדיקות" : "Checks"}: ${result.checks.map((c) => `${c.id}=${c.status}`).join(", ")}`
  );
  lines.push(
    `${he ? "הנחות" : "Assumptions"}: CPI ${formatPercent(assumptions.cpiAnnual, 1)}/yr, +${assumptions.stressShockPoints}pp`
  );
  lines.push("");
  lines.push(
    he
      ? "הופק על ידי VryfID. סימולציה לימודית, לא הצעת בנק."
      : "Generated by VryfID. Educational simulation, not a bank quote."
  );
  return lines.join("\n");
}

export function ExportPanel({
  profile,
  mix,
  result,
  assumptions,
  onPrint,
}: {
  profile: BorrowerProfile;
  mix: Mix;
  result: MixResult;
  assumptions: Assumptions;
  onPrint: (mode: PrintMode) => void;
}) {
  const { t, lang } = useLang();
  const [copied, setCopied] = useState(false);

  async function copySummary() {
    try {
      track("summary_copied", { lang });
      await navigator.clipboard.writeText(buildTextSummary(profile, mix, result, assumptions, lang));
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // clipboard unavailable — no-op
    }
  }

  return (
    <div
      className="rounded-2xl p-5"
      style={{ background: softCardGradient, border: softCardBorder, boxShadow: softCardShadow }}
    >
      <p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-navy/45">{t.export.title}</p>
      <p className="mt-1 text-sm text-navy-mid/70">{t.export.sub}</p>

      <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3">
        <button
          onClick={() => {
            track("pdf_download_started", { mode: "he" });
            onPrint("he");
          }}
          className="rounded-full bg-navy px-5 py-3 text-sm font-semibold text-cream transition-all duration-200 active:scale-[0.98]"
          style={{ boxShadow: navySelectedShadow }}
        >
          {t.export.printHebrew}
        </button>
        <button
          onClick={() => {
            track("pdf_download_started", { mode: "en" });
            onPrint("en");
          }}
          className="rounded-full bg-navy px-5 py-3 text-sm font-semibold text-cream transition-all duration-200 active:scale-[0.98]"
          style={{ boxShadow: navySelectedShadow }}
        >
          {t.export.printEnglish}
        </button>
        <button
          onClick={() => {
            track("pdf_download_started", { mode: "both" });
            onPrint("both");
          }}
          className="rounded-full bg-navy px-5 py-3 text-sm font-semibold text-cream transition-all duration-200 active:scale-[0.98]"
          style={{ boxShadow: navySelectedShadow }}
        >
          {t.export.printBoth}
        </button>
      </div>

      <div className="mt-3">
        <button
          onClick={copySummary}
          className={`w-full rounded-full border px-6 py-3 text-sm font-semibold transition-all duration-200 active:scale-[0.98] ${
            copied
              ? "border-good bg-good/10 text-good"
              : "border-warm-border bg-white text-navy-mid/80 hover:border-navy hover:text-navy"
          }`}
        >
          {copied ? t.export.copied : t.export.copyBtn}
        </button>
      </div>

      <ShareLinks placement="export_panel" className="mt-4 justify-start" />

      <div className="mt-6 border-t border-navy/10 pt-4">
        <p className="font-semibold text-navy">{t.export.banksTitle}</p>
        <p className="mt-1 text-xs leading-relaxed text-navy-mid/60">{t.export.banksNote}</p>
        <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">
          {BANKS.map((bank) => (
            <div
              key={bank.nameEn}
              className="flex items-center justify-between gap-3 rounded-xl border border-warm-border bg-white px-4 py-3"
              style={{ boxShadow: softCardShadow }}
            >
              <div className="flex items-center gap-3">
                <div
                  className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-sm font-bold text-white shadow-sm"
                  style={{ backgroundColor: bank.color }}
                  aria-hidden="true"
                >
                  {bank.mark}
                </div>
                <div>
                <p className="text-sm font-semibold text-navy">{lang === "he" ? bank.nameHe : bank.nameEn}</p>
                <p className="text-xs text-navy-mid/55" dir="ltr">
                  {t.export.call} {bank.phone}
                </p>
                </div>
              </div>
              <a
                href={bank.url}
                target="_blank"
                rel="noreferrer"
                onClick={() => track("bank_link_clicked", { bank: bank.nameEn })}
                className="shrink-0 rounded-full border border-warm-border px-3 py-1.5 text-xs font-semibold text-navy-mid/70 transition-colors hover:border-navy hover:text-navy"
              >
                {t.export.visit} ↗
              </a>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
